/mob/proc/AdjustGrit(option, val)
    var/maxGrit = 20 + (20 * AscensionsAcquired)
    switch(option)
        if("add")
            if(passive_handler["Grit"] + val <= maxGrit)
                passive_handler.Increase("Grit", round(val, 0.1))
        if("sub")
            if(passive_handler["Grit"] - val >= 1)
                passive_handler.Decrease("Grit", round(val, 0.1))
        if("reset")
            passive_handler["Grit"] = 1
